---
fluxbb_domain: bbs.archlinux.org
fluxbb_dir: /srv/http/fluxbb

fluxbb_cookie_name: flux_cookie_eezohm0o
fluxbb_funnyquestion_hash: aixuGahCh4eng3bu
fluxbb_version: 3e9fba035f2273c70ed2d4a609cc9ecbdc820116
