---

- name: install dovecot
  pacman: name=dovecot,pigeonhole state=present

- name: install dovecot.conf
  template: src=dovecot.conf.j2 dest=/etc/dovecot/dovecot.conf owner=root group=root mode=0644
  notify:
    - reload dovecot

- name: start and enable dovecot
  service: name=dovecot enabled=yes state=started

