---

- name: restart postfix
  service: name=postfix state=restarted

- name: reload postfix
  command: postfix reload

- name: postmap relay_passwords
  command: postmap /etc/postfix/relay_passwords
