---
- name: install php-fpm
  pacman: name=php-fpm state=present

- name: install php-fpm@ service
  copy: >
    src=php-fpm@.service dest=/etc/systemd/system/php-fpm@.service
    owner=root group=root mode=0644
  notify: daemon reload
