---

- name: install git
  pacman: name=git,python2,python2-virtualenv state=present

- name: make archweb user
  user: name=archweb shell=/bin/false home="{{ archweb_home }}" createhome=no

- name: fix home permissions
  file: state=directory owner=archweb group=archweb path="{{ archweb_home }}"

- name: clone archweb repo
  git: repo=git://git.archlinux.org/archweb.git dest="{{ archweb_home }}"
  become: true
  become_user: archweb

- name: make virtualenv
  command: virtualenv2 "{{ archweb_home }}"/env creates="{{ archweb_home }}/env/bin/python"
  become: true
  become_user: archweb

- name: install stuff into virtualenv
  pip: requirements="{{ archweb_home }}/requirements_prod.txt" virtualenv="{{ archweb_home }}/env"
  become: true
  become_user: archweb

- name: fix home permissions
  file: state=directory owner=archweb group=archweb path="{{ archweb_home }}"

- name: copy archweb services
  copy: src="{{ item }}" dest="/etc/systemd/system/{{ item }}" owner=root group=root mode=0644
  with_items:
    - archweb-reporead.service
    - archweb-mirrorcheck.service
    - archweb-mirrorcheck.timer
  notify:
    - daemon reload

- name: configure archweb
  template: src=local_settings.py.j2 dest=/srv/http/archweb/local_settings.py owner=archweb group=archweb mode=0660

- name: start and enable archweb services
  service: name="{{ item }}" enabled=yes state=started
  with_items:
    - archweb-reporead.service
    - archweb-mirrorcheck.timer
