---

- name: install ldap
  pacman: name=389-ds-base state=present



- name: open firewall hole
  firewalld: service=ldap permanent=true state=enabled immediate=yes
  when: configure_firewall
  tags:
    - firewall
