version: 1

formatters:
    journal_fmt:
        format: '%(name)s: [%(request)s] %(message)s'

handlers:
    buffer:
        class: logging.handlers.MemoryHandler
        target: journal
        capacity: 10
        flushLevel: 30  # Flush for WARNING logs as well

    journal:
        class: systemd.journal.JournalHandler
        formatter: journal_fmt
        SYSLOG_IDENTIFIER: synapse

loggers:
    twisted:
        handlers: [journal]
        propagate: false

root:
    level: WARNING
    handlers: [buffer]

disable_existing_loggers: false
