version: 1

formatters:
    journal_fmt:
        format: '%(name)s: [%(request)s] %(message)s'

handlers:
    journal:
        class: systemd.journal.JournalHandler
        formatter: journal_fmt
        SYSLOG_IDENTIFIER: synapse

loggers:
    synapse.logging.context:
        level: ERROR

root:
    level: WARNING
    handlers: [journal]

disable_existing_loggers: false
