worker_app: synapse.app.media_repository
worker_listeners:
  - port: 8013
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [media]
        compress: false

# vim:ft=yaml sw=2 et:
