---

- name: ensure latest keyring
  pacman:
    name: archlinux-keyring
    state: latest
    update_cache: yes

- name: upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes
  register: pacman_upgrade

- name: wait for svntogit to finish
  wait_for:
    path: /srv/svntogit/update-repos.sh.lock
    state: absent
  when: inventory_hostname == "gemini.archlinux.org"

- name: reboot
  reboot:
  when: pacman_upgrade is changed
