---

- name: ensure latest keyring
  pacman:
    name: archlinux-keyring
    state: latest
    update_cache: yes

- name: upgrade all packages
  pacman:
    update_cache: yes
    upgrade: yes
  register: pacman_upgrade

- name: check for running builds
  block:
    - name: list build-related processes
      command: pgrep -x 'mkarchroot|makechrootpkg|systemd-nspawn'
      register: pgrep
      ignore_errors: true

    - name: abort reboot with running builds
      meta: end_host
      when: pgrep is succeeded
  when: "'buildservers' in group_names"


- name: check for active borg backup jobs
  block:
    - name: get service facts
      service_facts:

    - name: abort reboot when borg backup is running
      meta: end_host
      when: >
        ansible_facts.services["borg-backup.service"]["state"] == "running" or
        ansible_facts.services["borg-backup-offsite.service"]["state"] == "running"
  when: "'borg_clients' in group_names"

- name: gemini pre-reboot checks
  block:
    - name: list logged on users
      command: who
      register: who

    - name: abort reboot with logged on users
      meta: end_host
      when:
        - who is changed
        - who.stdout_lines|length > 1

    - name: stop arch-svntogit.timer
      service: name=arch-svntogit.timer state=stopped

    - name: wait for svntogit to finish
      wait_for:
        path: /srv/svntogit/update-repos.sh.lock
        state: absent
  when: inventory_hostname == "gemini.archlinux.org"

- name: reboot
  reboot:
  when: pacman_upgrade is changed
