---
- name: restart mailman
  service: name=mailman daemon_reload=yes state=restarted

- name: reload mailman
  service: name=mailman state=reloaded

- name: reload postfix
  service: name=postfix state=reloaded
