---

- name: install postfix
  pacman: name=postfix state=present

- name: install template configs
  template: src={{item}}.j2 dest=/etc/postfix/{{item}} owner=root group=root mode=0644
  notify:
    - reload postfix
  with_items:
    - main.cf
    - master.cf
    - transport
    - aliases

- name: install additional files
  copy: src={{item}} dest=/etc/postfix/{{item}} owner=root group=root mode=0644
  with_items:
    - access_client
    - access_sender
    - access_sender-post-filter
    - access_helo
    - access_recipient
    - body_checks
    - header_checks
    - relocated
    - compat_maps

- name: update aliases db
  command: postalias /etc/postfix/aliases

- name: postmap additional files
  command: postmap /etc/postfix/{{item}}
  with_items:
    - access_client
    - access_sender
    - access_sender-post-filter
    - access_helo
    - access_recipient
    - transport
    - relocated
    - compat_maps

- name: create dhparam 2048
  command: openssl dhparam -out /etc/postfix/dh2048.pem 2048 creates=/etc/postfix/dh2048.pem
  notify:
    - reload postfix

- name: create dhparam 512
  command: openssl dhparam -out /etc/postfix/dh_512.pem 512 creates=/etc/postfix/dh_512.pem
  notify:
    - reload postfix

- name: start and enable postfix
  service: name=postfix enabled=yes state=started
