---

- name: install packages
  pacman: name=zabbix-agent

- file: path=/etc/zabbix state=directory owner=root group=root mode=755

- name: create host PSK
  shell: umask 077; head -c100 /dev/urandom | sha512sum | cut -d " " -f1 > /etc/zabbix/zabbix_agentd.psk creates=/etc/zabbix/zabbix_agentd.psk

- name: fix permissions of PSK file
  file: path=/etc/zabbix/zabbix_agentd.psk owner=zabbix-agent group=zabbix-agent mode=600

- name: install agent config
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf owner=zabbix-agent group=zabbix-agent mode=600
  notify:
    - restart zabbix agent

- name: Create mysql config for agent checks
  template: src=my.cnf.j2 dest=/etc/zabbix/zabbix_agentd.my.cnf owner=zabbix-agent group=zabbix-agent mode=600
  when: zabbix_agent_mysql_user is defined

- name: run zabbix agent service
  service: name=zabbix-agent enabled=yes state=started

