---

prometheus_domain: monitoring.archlinux.org

prometheus_textfile_dir: /var/lib/node_exporter

prometheus_exporter_port: '9100'

gitlab_runner_exporter_port: '9252'

prometheus_mysqld_user: mysqld_exporter
prometheus_mysqld_exporter_port: '9104'
