---

- name: fetch ssh hostkey checkums
  hosts: all
  tasks:
      - name: fetch hostkey checksums
        shell: "for type in sha256 md5; do for file in /etc/ssh/ssh_host_*.pub; do ssh-keygen -l -f $file -E $type; done; echo; done"
        register: ssh_hostkeys

- name: store hostkeys
  hosts: 127.0.0.1
  tasks:
      - name: store hostkeys
        copy:
            dest: "{{playbook_dir}}/../../docs/ssh-hostkeys.txt"
            content: "{% for host in groups['all'] | sort %}# {{host}}\n{{hostvars[host].ssh_hostkeys.stdout}}\n\n{% endfor %}"
