---

- name: upgrade and reboot all hetzner servers
  hosts: all,!kape_servers,!packet_net,!rsync_net,!hetzner_storageboxes
  serial: 20%
  gather_facts: false

  tasks:
    - name: upgrade each host in this batch
      include_tasks: include/upgrade-server.yml

- name: upgrade and reboot all kape and packet.net servers
  hosts: kape_servers,packet_net
  serial: 1
  gather_facts: false

  tasks:
    - name: upgrade each host in this batch
      include_tasks: include/upgrade-server.yml
