---

- name: read /etc/motd
  command: cat /etc/motd
  register: motd_contents
  changed_when: motd_contents.stdout | length > 0

- name: check whether we're running in the Hetzner rescue system
  fail: msg="Not running in Hetzner rescue system!"
  when: "'Hetzner Rescue' not in motd_contents.stdout"

- name: create GRUB embed partitions
  command: sgdisk -g --clear -n 1:0:+10M {{ item }} -c 1:boot -t 1:ef02
  with_items:
    - "{{ system_disks }}"
  register: sgdisk
  changed_when: "sgdisk.rc == 0"

- name: create root partitions
  command: sgdisk -n 2:0:0 {{ item }} -c 2:root
  with_items:
    - "{{ system_disks }}"
  register: sgdisk
  changed_when: "sgdisk.rc == 0"

- name: partition and format the disks (btrfs RAID)
  command: mkfs.btrfs -f -L root -d {{ raid_level|default('raid1') }} -m {{ raid_level|default('raid1') }} -O no-holes {{ system_disks | map('regex_replace', '^(.*)$', '\1p2') | join(' ') }}
  when: filesystem == "btrfs" and system_disks|length == 2

- name: partition and format the disks (btrfs single)
  command: mkfs.btrfs -f -L root -d single -m single -O no-holes {{ system_disks[0] }}p2
  when: filesystem == "btrfs" and system_disks|length == 1

- name: create MDADM array
  command: mdadm --create --level=1 --raid-devices=2 --run /dev/md0 {{ system_disks | map('regex_replace', '(.*)', '^\1p2$') | join(' ') }}
  when: filesystem != "btrfs" and system_disks|length == 2

- name: format the MDADM array
  filesystem: dev=/dev/md0 fstype={{ filesystem|default('ext4') }}
  when: filesystem != "btrfs" and system_disks|length == 2

- name: mount the filesystem (btrfs)
  mount: src="{{ system_disks[0] }}p2" path=/mnt state=mounted fstype=btrfs opts="compress=zstd,space_cache=v2"
  when: filesystem == "btrfs"

- name: mount the filesystem (ext4 RAID)
  mount: name=/mnt src=/dev/md0 state=mounted fstype={{ filesystem|default('ext4') }}
  when: filesystem != "btrfs" and system_disks|length == 2

- name: touch LOCK file on mountpoint
  file: path=/mnt/LOCK state=touch

- name: download bootstrap image
  get_url:
    url: https://mirrors.kernel.org/archlinux/iso/{{ bootstrap_version }}/archlinux-bootstrap-{{ bootstrap_version }}-x86_64.tar.gz
    dest: /tmp/

- name: extract boostrap image
  unarchive:
    src: /tmp/archlinux-bootstrap-{{ bootstrap_version }}-x86_64.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/root.x86_64

- name: copy resolv.conf to bootstrap chroot
  copy: remote_src=True src=/etc/resolv.conf dest=/tmp/root.x86_64/etc/resolv.conf

- name: mount /proc to bootstrap chroot
  mount:
    src: /proc
    path: /tmp/root.x86_64/proc
    opts: rbind
    state: mounted
    fstype: none
    fstab: /tmp/dummyfstab

- name: mount /sys to bootstrap chroot
  mount:
    src: /sys
    path: /tmp/root.x86_64/sys
    opts: rbind
    state: mounted
    fstype: none
    fstab: /tmp/dummyfstab

- name: mount /dev to bootstrap chroot
  mount:
    src: /dev
    path: /tmp/root.x86_64/dev
    opts: rbind
    state: mounted
    fstype: none
    fstab: /tmp/dummyfstab

- name: mount /mnt to bootstrap chroot
  mount:
    src: /mnt
    path: /tmp/root.x86_64/mnt
    opts: rbind
    state: mounted
    fstype: none
    fstab: /tmp/dummyfstab

- name: configure pacman mirror
  template: src=mirrorlist.j2 dest=/tmp/root.x86_64/etc/pacman.d/mirrorlist owner=root group=root mode=0644

- name: initialize pacman keyring inside bootstrap chroot
  command: chroot /tmp/root.x86_64 pacman-key --init
  register: chroot_pacman_key_init
  changed_when: "chroot_pacman_key_init.rc == 0"

- name: populate pacman keyring inside bootstrap chroot
  command: chroot /tmp/root.x86_64 pacman-key --populate archlinux
  register: chroot_pacman_key_populate
  changed_when: "chroot_pacman_key_populate.rc == 0"

- name: install ucode update for Intel
  set_fact: ucode="intel-ucode"
  when: "'GenuineIntel' in ansible_facts['processor']"

- name: install ucode update for AMD
  set_fact: ucode="amd-ucode"
  when: "'AuthenticAMD' in ansible_facts['processor']"

- name: install arch base from bootstrap chroot
  command: chroot /tmp/root.x86_64 pacstrap /mnt base linux btrfs-progs grub openssh python-requests python-yaml {{ ucode }}
  args:
    creates: /tmp/root.x86_64/mnt/bin

- name: mount /proc to new chroot
  mount:
    src: /proc
    path: /mnt/proc
    opts: rbind
    state: mounted
    fstype: none
    fstab: /dev/dummyfstab

- name: mount /sys to new chroot
  mount:
    src: /sys
    path: /mnt/sys
    opts: rbind
    state: mounted
    fstype: none
    fstab: /dev/dummyfstab

- name: mount /dev to new chroot
  mount:
    src: /dev
    path: /mnt/dev
    opts: rbind
    state: mounted
    fstype: none
    fstab: /dev/dummyfstab

- name: generate mdadm.conf
  shell: mdadm --detail --scan >> /mnt/etc/mdadm.conf
  when: filesystem != "btrfs"

- name: configure locale.gen
  lineinfile: dest=/mnt/etc/locale.gen line="en_US.UTF-8 UTF-8"

- name: run locale-gen inside chroot
  command: chroot /mnt locale-gen
  register: chroot_locale_gen
  changed_when: "chroot_locale_gen.rc == 0"

- name: run systemd-firstboot
  command: chroot /mnt systemd-firstboot --locale=en_US.UTF-8 --timezone=UTC --hostname={{ hostname }}
  register: chroot_systemd_firstboot
  changed_when: "chroot_systemd_firstboot.rc == 0"

- name: add mdadm_udev to mkinitcpio.conf
  lineinfile:
    dest: /mnt/etc/mkinitcpio.conf
    backrefs: yes
    regexp: '^(.*)block filesystems(.*)$'
    line: '\1block mdadm_udev filesystems\2'
  when: filesystem != "btrfs"

- name: run mkinitcpio
  command: chroot /mnt mkinitcpio -p linux
  register: chroot_mkinitcpio
  changed_when: "chroot_mkinitcpio.rc == 0"

- name: configure network (static)
  template: src=10-static-ethernet.network.j2 dest=/mnt/etc/systemd/network/10-static-ethernet.network owner=root group=root mode=0644
  when: not dhcp|default(False)

- name: configure network (dhcp)
  template: src=10-dhcp-ethernet.network.j2 dest=/mnt/etc/systemd/network/10-dhcp-ethernet.network owner=root group=root mode=0644
  when: dhcp|default(False)

- name: install hcloud-init
  copy: src=hcloud-init dest=/mnt/usr/local/bin/hcloud-init owner=root group=root mode=0755
  when: "'hcloud' in group_names"

- name: install hcloud-init.service
  copy: src=hcloud-init.service dest=/mnt/etc/systemd/system/hcloud-init.service owner=root group=root mode=0644
  when: "'hcloud' in group_names"

- name: enable hcloud-init inside chroot
  command: chroot /mnt systemctl enable hcloud-init
  register: chroot_systemd_services
  changed_when: "chroot_systemd_services.rc == 0"
  when: "'hcloud' in group_names"

- name: provide default mount options (btrfs)
  lineinfile:
    path: /mnt/etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"rootflags=compress=zstd\""
  when: filesystem == "btrfs"

- name: install grub
  command: chroot /mnt grub-install --recheck {{ item }}
  with_items:
    - "{{ system_disks }}"
  register: chroot_grub_install
  changed_when: "chroot_grub_install.rc == 0"

- name: configure grub
  command: chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
  register: chroot_grub_mkconfig
  changed_when: "chroot_grub_mkconfig.rc == 0"

- name: enable services inside chroot
  command: chroot /mnt systemctl enable sshd systemd-networkd systemd-resolved fstrim.timer
  register: chroot_systemd_services
  changed_when: "chroot_systemd_services.rc == 0"

- name: assign pubkey list to fact
  set_fact: pubkey_list="{{ lookup('file', "{{ playbook_dir }}/../../pubkeys/" + item) }}"
  register: pubkeys
  with_items: "{{ root_ssh_keys }}"

- name: assign pubkey string to fact
  set_fact: pubkey_string={{ pubkeys.results | map(attribute='ansible_facts.pubkey_list') | join('\n') }}

- name: add authorized key for root
  authorized_key: user=root key="{{ pubkey_string }}" path=/tmp/root.x86_64/mnt/root/.ssh/authorized_keys exclusive=yes

- name: configure sshd
  template: src=sshd_config.j2 dest=/mnt/etc/ssh/sshd_config owner=root group=root mode=0644

- name: create symlink to resolv.conf
  file: src=/run/systemd/resolve/stub-resolv.conf dest=/mnt/etc/resolv.conf state=link force=yes

- name: clean pacman cache
  command: chroot /mnt pacman -Scc --noconfirm
  register: chroot_pacman_clean_cache
  changed_when: "chroot_pacman_clean_cache.rc == 0"

- name: remove LOCK file on mountpoint
  file: path=/mnt/LOCK state=absent
