---

- name: create wkd user
  user: name={{ wkd_user }} shell=/bin/false home={{ wkd_home }}

- name: install wkd update script
  copy: src=update-wkd.sh dest=/usr/local/bin/update-wkd.sh owner=root group=root mode=0755

- name: install wkd service
  template: src=update-wkd.service.j2 dest=/etc/systemd/system/update-wkd.service owner=root group=root mode=0644
  notify:
    - daemon reload
    - run wkd service

- name: create pacman.d hooks dir
  file: state=directory path=/etc/pacman.d/hooks mode=0755 owner=root group=root

- name: install pgp_import hook
  template: src=update-wkd-pacman-hook.j2 dest=/etc/pacman.d/hooks/update-wkd.hook owner=root group=root mode=0644

- name: create ssl cert
  include_role:
    name: certificate
  vars:
    domains: ["{{ wkd_domain }}"]

- name: create wkd_dir
  file: state=directory owner={{ wkd_user }} group={{ wkd_user }} path="{{ wkd_dir }}" mode=0755

- name: set up nginx
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/wkd.conf owner=root group=root mode=644
  notify: reload nginx
  tags: ['nginx']

- name: make nginx log dir
  file: path=/var/log/nginx/{{ wkd_domain }} state=directory owner=root group=root mode=0755
