configure_firewall: true

# this is needed to make ansible find the firewalld python
# module when deploying firewalld tasks
ansible_python_interpreter: /usr/bin/python3

zabbix_agent_templates:
  - Template OS Linux
