---

- name: install opendkim
  pacman: name=opendkim state=present

- name: install opendkim.conf
  template: src=opendkim.conf.j2 dest=/etc/opendkim/opendkim.conf owner=root group=root mode=644
  notify:
    - restart opendkim

- name: install domains config
  template: src=domains.j2 dest=/etc/opendkim/domains owner=root group=root mode=644
  notify:
    - restart opendkim

- file: path="/etc/opendkim/private" state=directory owner=root group=root mode=0700

- name: generate DKIM key for {{dkim_selector}}
  command: opendkim-genkey -r -s {{dkim_selector}} -d archlinux.org --bits=4096 creates=/etc/opendkim/private/{{dkim_selector}}.private

- name: start and enable opendkim
  service: name=opendkim enabled=yes state=started

