---

- name: install packages
  pacman: name={{ item }} state=present
  with_items:
    - git
    - python
    - python-sqlalchemy
    - python-flask
    - python-flask-sqlalchemy
    - python-flask-wtf
    - python-flask-login
    - python-requests
    - python-scrypt
    - pyalpm
    - sqlite
    - expac
    - uwsgi-plugin-python

- name: make security user
  user: name=security shell=/bin/false home="{{ security_tracker_dir }}" createhome=no

- name: fix home permissions
  file: state=directory owner=security group=security path="{{ security_tracker_dir }}"

- name: clone security-tracker repo
  git: repo=https://github.com/anthraxx/arch-security-tracker.git version="stable" dest="{{ security_tracker_dir }}"
  become: true
  become_user: security

- name: run initial setup
  become: true
  become_user: security
  command: /usr/bin/make chdir="{{ security_tracker_dir }}" creates=*.db

- name: fix home permissions
  file: state=directory owner=security group=security path="{{ security_tracker_dir }}"

- name: set up nginx
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/security-tracker.conf owner=root group=root mode=644
  notify:
    - restart nginx

- name: make nginx log dir
  file: path=/var/log/nginx/{{ security_tracker_domain }} state=directory owner=http group=log mode=755

- name: copy security-tracker units
  copy: src="{{ item }}" dest="/etc/systemd/system/{{ item }}" owner=root group=root mode=0644
  with_items:
    - security-tracker-update.timer
    - security-tracker-update.service
  notify:
    - daemon reload

- name: configure security-tracker
  template: src=20-user.local.conf.j2 dest={{ security_tracker_dir }}/config/20-user.local.conf owner=security group=security mode=0640

- name: deploy security-tracker
  template: src=security-tracker.ini.j2 dest=/etc/uwsgi/vassals/security-tracker.ini owner=security group=http mode=0644

- name: start and enable security-tracker timer
  service: name="security-tracker-update.timer" enabled=yes state=started
