---
- name: set up nginx
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/patchwork.conf owner=root group=root mode=644
  notify:
    - reload nginx

- name: make nginx log dir
  file: path=/var/log/nginx/{{ patchwork_domain }} state=directory owner=root group=log mode=750
