---
- name: make patchwork user
  user: name=patchwork shell=/bin/false home="{{ patchwork_dir }}" createhome=no

- name: fix home permissions
  file: state=directory owner=patchwork group=patchwork path="{{ patchwork_dir }}"

- name: set up nginx
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/patchwork.conf owner=root group=root mode=644
  notify:
    - reload nginx

- name: make nginx log dir
  file: path=/var/log/nginx/{{ patchwork_domain }} state=directory owner=root group=log mode=750

- name: deploy maintenance page
  template: src=503.html.j2 dest="{{ patchwork_dir }}/503.html" owner=patchwork group=patchwork mode=644
