---

- name: systemd daemon reload
  command: systemctl daemon-reload

- name: restart spampd
  service: name=spampd state=restarted

- name: restart sa-update
  service: name=sa-update state=restarted
