- name: install packages
  package:
    name: "postgrey"
    state: "present"

- name: install local whitelist template
  template:
    src: "whitelist_clients.local.j2"
    dest: "/etc/postfix/postgrey_whitelist_clients.local"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart postgrey

- name: create service unit override path
  file:
    path: "/etc/systemd/system/postgrey.service.d/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 755

- name: install service unit override file
  template:
    src: "service-override.j2"
    dest: "/etc/systemd/system/postgrey.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - restart postgrey
