---
backup_hosts:
  - host: "ssh://u236610.your-storagebox.de:23"
    dir: "~/repo"
    suffix: ""
    borg_cmd: "borg"
  - host: "ssh://{{ rsync_net_username }}@zh1905.rsync.net:22"
    dir: "~/backup/{{ inventory_hostname }}"
    suffix: "-offsite"
    borg_cmd: "borg --remote-path=borg1"
