---
backup_hosts:
  - host: "ssh://u236610.your-storagebox.de:23"
    dir: "~/repo"
    suffix: ""
  - host: "ssh://{{ rsync_net_username }}@prio.ch-s012.rsync.net:22"
    dir: "~/backup/{{ inventory_hostname }}"
    suffix: "-offsite"
