---
- name: install mariadb
  pacman: name=mariadb,mysql-python state=present

- name: initialize mariadb
  command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
    creates: /var/lib/mysql/mysql

- name: configure mariadb
  template: src=server.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
    - restart mariadb

- name: start and enable the service
  service: name=mariadb state=started enabled=yes

- name: enable systemd ressource accounting
  command: systemctl set-property mariadb CPUAccounting=yes MemoryAccounting=yes

- name: delete anonymous users
  mysql_user: user='' host_all=yes state='absent'

- name: disallow remote root login
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: drop test database
  mysql_db: db=test state=absent

- name: set root password
  mysql_user: user=root host={{ item }} password={{ mariadb_users.root }}
  with_items:
    - '127.0.0.1'
    - '::1'
    - 'localhost'
  no_log: true

- name: create client configuration for root
  template: src=client.cnf.j2 dest=/root/.my.cnf
  no_log: true

- name: configure zabbix-agent user
  mysql_user: user={{zabbix_agent_mysql_user}} host=localhost password={{mariadb_users.zabbix_agent}}

- name: install zabbix mysql config
  template: src=zabbix_agentd.my.cnf.j2 dest=/etc/zabbix/zabbix_agentd.my.cnf owner=zabbix-agent group=zabbix-agent mode=0600

  # the source addresses here could be tightened up more, but it's far better
  # than having mariadb open to the world
- name: open firewall holes to other infrastructure hosts
  firewalld: service=mysql permanent=true state=enabled source={{item}}
  with_items: "{{ groups['all'] }}"
