---
archweb_dir: '/srv/http/archweb'
archweb_domain: 'www.archlinux.org'
archweb_alternate_domains: ['archlinux.org']
archweb_site: true
archweb_mirrorcheck: false
archweb_pgp_import: false
archweb_keyring: '/etc/pacman.d/gnupg/pubring.gpg'
archweb_reporead: false
archweb_services: false

archweb_db: 'archweb'
archweb_db_host: 'localhost'
archweb_db_site_user: 'archweb'
archweb_db_services_user: 'archweb_services'
archweb_db_services_table_objs: 'ALL_IN_SCHEMA'
archweb_db_services_sequence_objs: 'ALL_IN_SCHEMA'
archweb_db_dbscripts_user: 'archweb_dbscripts'
archweb_db_dbscripts_table_objs: 'mirrors_mirror,mirrors_mirrorrsync'
archweb_db_backup_user: 'archweb_backup'
archweb_db_backup_table_objs: 'ALL_IN_SCHEMA'
archweb_db_backup_sequence_objs: 'ALL_IN_SCHEMA'
