version: '3.8'
services:
    keycloak:
        container_name: keycloak
        ports:
            - '9000:8080'
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_DEFAULT_THEME=archlinux
            - KEYCLOAK_WELCOME_THEME=archlinux
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./archlinux:/opt/jboss/keycloak/themes/archlinux
