---

- name: install additional buildserver support packages
  pacman: name={{item}} state=present
  with_items:
    - appstream-generator

- name: install archbuild
  pacman: name=systemd-swap,devtools,zsh,git,subversion,mercurial,bzr,xdelta3,ruby,tig,colordiff state=present

- name: install archbuild scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - mkpkg
    - diffrepo
    - clean-chroots
    - clean-dests
    - gitpkg

- name: install archbuild units
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - clean-chroots.timer
    - clean-chroots.service
    - clean-dests.timer
    - clean-dests.service
    - var-lib-archbuilddest.mount
    - strictatime@.service
  notify:
    - daemon reload

- name: install archbuild unit
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - var-lib-archbuild.mount
  notify:
    - daemon reload
  when: archbuild_fs == 'tmpfs'

- name: install archbuild user units
  copy: src={{ item }} dest=/etc/systemd/user/{{ item }} owner=root group=root mode=0644
  with_items:
    - mkpkg@.timer
    - mkpkg@.service

- name: install systemd-swap config
  copy: src=swap.conf dest=/etc/systemd/swap.conf owner=root group=root mode=0644
  when: archbuild_fs == 'tmpfs'

- name: start and enable archbuild mounts
  service: name={{ item }} enabled=yes state=started
  with_items:
    - systemd-swap.service
    - var-lib-archbuild.mount
  when: archbuild_fs == 'tmpfs'

- name: start and enable archbuilddest mount
  service: name={{ item }} enabled=yes state=started
  with_items:
    - var-lib-archbuilddest.mount

- name: create archbuilddest
  file:
    state: directory
    path: '/var/lib/{{ "/".join(item) }}'
    owner: root
    group: root
    mode: 0775
  with_nested:
    - [archbuilddest]
    - [srcdest]

- name: set acl on archbuilddest
  acl:
    name: '/var/lib/archbuilddest/{{ item[0] }}'
    state: present
    entry: '{{ item[1] }}'
  with_nested:
    - [srcdest]
    - ['user::rwx',
       'group::r-x',
       'group:dev:rwx',
       'group:tu:rwx',
       'other::r-x',
       'mask::rwx',
       'default:user::rwx',
       'default:group::r-x',
       'default:group:dev:rwx',
       'default:group:tu:rwx',
       'default:other::r-x',
       'default:mask::rwx']

- name: start and enable archbuild units
  service: name={{ item }} enabled=yes state=started
  with_items:
    - clean-chroots.timer
    - clean-dests.timer

- name: install makepkg.conf
  template: src=makepkg.conf.j2 dest=/etc/makepkg.conf owner=root group=root mode=0644

- name: install archbuild sudoers config
  copy: src=sudoers dest=/etc/sudoers.d/archbuild
