---

- name: install packages
  pacman: name=zabbix-server,zabbix-frontend-php

- file: path=/etc/zabbix state=directory owner=root group=root mode=755

- name: install server config
  template: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf owner=zabbix-server group=zabbix-server mode=600
  notify:
    - restart zabbix server

- name: install nginx config
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/zabbix.conf owner=root group=root mode=644
  notify:
    - reload nginx

- name: make nginx log dir
  file: path=/var/log/nginx/{{ zabbix_domain }} state=directory owner=root group=root mode=0755

- name: create zabbix db user
  postgresql_user: name={{ zabbix_db_user }} password={{ zabbix_db_password }}
  become: yes
  become_user: postgres
  become_method: su

- name: create zabbix db
  postgresql_db: db="{{zabbix_db_name}}" owner={{zabbix_db_user}}
  become: yes
  become_user: postgres
  become_method: su

- name: create zabbix .pgpass
  template: src=pgpass.j2 dest="{{zabbix_pgpass}}" owner=zabbix-server group=zabbix-server mode=600
  no_log: true

- name: install database schema
  shell: psql -U "{{zabbix_db_user}}" "{{zabbix_db_name}}" < "/usr/share/zabbix-server/postgresql/{{item}}"
  become_user: zabbix-server
  become: yes
  with_items:
    - schema.sql
    - images.sql
    - data.sql

- name: make zabbix web user
  user: name=zabbix-web shell=/bin/false home="{{ zabbix_web_dir }}" createhome=no

- name: configure php-fpm
  template:
    src=php-fpm.conf.j2 dest="/etc/php/php-fpm.d/zabbix-web.conf"
    owner=root group=root mode=0644
  notify:
    - restart php-fpm@zabbix-web

- name: install zabbix web config
  template: src=zabbix.conf.php.j2 dest=/usr/share/webapps/zabbix/conf/zabbix.conf.php owner=zabbix-web group=zabbix-web mode=600

- name: run zabbix server service
  service: name=zabbix-server-pgsql enabled=yes state=started

- name: start and enable systemd socket
  service: name=php-fpm@zabbix-web.socket state=running enabled=true
