---
archweb_db_host: "{{ hostvars['archlinux.org']['wireguard_address'] }}"
geo_mirror_domain: "geo.mirror.pkgbuild.com"

# raise tcp window limits to 32MiB
tcp_rmem: "10240 87380 33554432"
tcp_wmem: "10240 87380 33554432"
