---

- name: daemon reload
  systemd:
    daemon-reload: yes

- name: restart php-fpm@{{ aurweb_user }}
  service: name=php-fpm@{{ aurweb_user }} state=restarted

- name: restart sshd
  service: name=sshd state=restarted
