- name: install sysadmin tools
  pacman: name={{ item }} state=present
  with_items:
    - lsof
    - psmisc
    - htop
    - nethogs
    - iftop
    - rsync
    - tmux
    - mtr
    - sshfs
    - dfc
    - tree
    - dstat
    - dmidecode
    - net-tools
    - ncdu
    - nmap
    - sysstat
    - iptraf-ng
    - vnstat
    - screen
    - tcpdump

- name: install misc utils
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - colordiff
    - multitail
    - httpie
    - the_silver_searcher
    - cloc
    - ipcalc
    - calc
    - wget
    - neovim
    - python2-neovim
    - vim
    - parallel
    - bash-completion
    - socat
    - pv
