---

- name: install sudo
  pacman: name=sudo state=present

# https://github.com/ansible/ansible/issues/11024
- name: remove all users from wheel group
  command: groupmems -g wheel --purge

- name: add sudo users to wheel
  user: name="{{ item }}" append=yes groups=wheel
  with_items: "{{ sudo_users }}"
  tags: ['archusers']

- name: allow wheel group to use sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel ALL=\(ALL\) ALL'
    insertafter: '^# %wheel ALL=\(ALL\) ALL'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
