version: '3.8'
services:
    keycloak:
        ports:
            - '9000:8080'
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_DEFAULT_THEME=archtheme
        image: jboss/keycloak
        volumes:
            - ./archtheme:/opt/jboss/keycloak/themes/archtheme