---

# make and gcc are required for sa-compile
- name: install spampd and dependencies
  pacman: name=spampd,make,gcc,razor state=present

- name: install sa-update.sh
  copy: src=sa-update.sh dest=/usr/local/bin/sa-update.sh owner=root group=root mode=0755
  notify:
    - restart sa-update

- name: install support files
  copy: src={{ item }} dest=/etc/mail/spamassassin/{{ item }} owner=root group=root mode=0644
  with_items:
    - update-gpgkeys
    - update-channels
    - yerp.gpg.key
    - zmi.gpg.key

- name: install systemd timers
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - sa-update.timer
    - sa-update.service
  notify:
    - systemd daemon reload

- name: create pacman.d hooks dir
  file: state=directory owner=root group=root path="/etc/pacman.d/hooks"

- name: install pacman sa-update hook
  copy: src=sa-update.hook dest=/etc/pacman.d/hooks/sa-update.hook owner=root group=root mode=0644

- name: create sa-update keyring directory
  file: path=/etc/mail/spamassassin/sa-update-keys mode=700 owner=root group=root state=directory

- name: add gpg keys to SA keyring
  command: /usr/bin/vendor_perl/sa-update --import "/etc/mail/spamassassin/{{item}}"
  with_items:
    - yerp.gpg.key
    - zmi.gpg.key

- name: install SA configs
  template: src={{item}}.j2 dest=/etc/mail/spamassassin/{{item}} owner=root group=root mode=0644
  notify:
    restart spampd
  loop:
    - local.cf
    - rules-en.cf

- name: check SA config validity
  command: /usr/bin/vendor_perl/spamassassin --lint

- name: activate systemd timers
  service: name={{ item }} enabled=yes state=started
  with_items:
    sa-update.timer

- name: remove override directory
  file: path=/etc/systemd/system/spampd.service.d/ state=absent
  notify:
    - systemd daemon reload
    - restart spampd

- name: start spampd
  service: name=spampd enabled=yes state=started
