---

- name: install borg
  pacman: name=borg state=present

- name: create borg user
  user: home="{{ backup_dir }}" name=borg

- name: create borg user home
  file: path="{{ backup_dir }}" state=directory owner=borg group=borg mode=0700

- name: create the root backup directory at {{ backup_dir }}
  file: path="{{ backup_dir }}/{{ item }}" state=directory owner=borg group=borg mode=0700
  with_items: "{{ backup_clients }}"

- name: fetch ssh keys
  command: cat /root/.ssh/id_rsa.pub
  register: ssh_keys
  delegate_to: "{{ groups[item][0] }}"
  with_items: "{{ backup_clients }}"

- name: allow certain clients to connect
  authorized_key:
    user=borg
    key="{{ item.stdout }}"
    manage_dir=yes
    key_options="command=\"/usr/bin/borg serve --restrict-to-path {{ backup_dir }}/{{ item['item'] }}\",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc"
  with_items: "{{ ssh_keys.results }}"
