---

- name: create reproducible build user
  user:
    name: "{{ item.key }}"
    group: users
    groups: "{{ item.value.groups | join(',') }}"
    comment: "{{ item.value.name}}"
    state: present
  with_dict: "{{ repro_users }}"

- name: configure ssh keys
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ lookup('file', '../roles/reprobuilds/files/' + item.value.ssh_key) }}"
    manage_dir: yes
    state: present
    exclusive: yes
  when: item.value.ssh_key is defined
  with_dict: "{{ repro_users }}"
