---

- name: install firewalld
  pacman:
    name: firewalld
    state: present

- name: start and enable firewalld
  service:
    name: firewalld
    enabled: "{{configure_firewall}}"
    state: "{{configure_firewall | ternary('started', 'stopped') }}"

- name: disable default dhcpv6-client rule
  firewalld:
    service: dhcpv6-client
    state: disabled
    immediate: yes
  when: configure_firewall
