---

- name: update pacman cache
  pacman: update_cache=yes

- name: install ntp
  pacman: name=ntp state=present

- name: start and enable ntp
  service: name=ntpd enabled=yes state=started

- name: install smart
  pacman: name=smartmontools state=present

- name: start and enable smart
  service: name=smartd enabled=yes state=started
  ignore_errors: yes # Ignore errors due to https://github.com/ansible/ansible-modules-core/issues/3868

- name: install mlocate
  pacman: name=mlocate state=present

- name: activate regular updatedb for mlocate
  service: name=updatedb.timer enabled=yes state=started

- name: generate locales
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8

- name: configure locales
  template: src=locale.conf.j2 dest=/etc/locale.conf owner=root group=root mode=0644

- name: generate ssh key for root
  command: ssh-keygen -b 4096 -N "" -f /root/.ssh/id_rsa creates="/root/.ssh/id_rsa"

- name: configure network
  template: src=10-static-ethernet.network.j2 dest=/etc/systemd/network/10-static-ethernet.network owner=root group=root mode=0644
  notify:
    - restart networkd

- name: install checkservices
  copy: src=archutils/checkservices dest=/usr/local/bin/checkservices owner=root group=root mode=0755
