---
- name: install required packages
  pacman: name=hefur

- name: create override dir
  file: path=/etc/systemd/system/hefurd.service.d state=directory

- name: copy systemd override
  template: src=override.conf.j2 dest=/etc/systemd/system/hefurd.service.d/override.conf owner=root group=root mode="u=rw,g=r,o=r"

- name: start and enable hefurd service
  service: name="hefurd.service" enabled=yes state=started

- name: open firewall hole for hefurd
  firewalld: port=6969/tcp permanent=true state=enabled immediate=yes
  when: configure_firewall
  tags:
    - firewall
