---

- name: install postgres
  pacman: name=postgresql,python2-psycopg2 state=present

- name: initialize postgres
  become: yes
  become_user: postgres
  become_method: su
  command: initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'
  args:
    chdir: /var/lib/postgres
    creates: /var/lib/postgres/data/postgresql.conf
  notify:
    - restart postgres

- name: configure postgres
  template: src={{ item }}.j2 dest=/var/lib/postgres/data/{{ item }} owner=postgres group=postgres mode=600
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify:
    - restart postgres

- name: start and enable postgres
  service: name=postgresql enabled=yes state=started

- name: set postgres user password
  postgresql_user: name=postgres password={{ postgres_users.postgres }}
  become: yes
  become_user: postgres
  become_method: su
