---

- name: setup apollo
  hosts: apollo
  remote_user: root
  roles:
    - common
    - tools
    - sshd
    - ssh_keys
    - { role: borg-client, backup_host: "borg@vostok.archlinux.org", backup_dir: "/backup/apollo", postgres_backup_dir: "/var/lib/postgres/backup" }
