---
- name: common playbook for archive-mirrors
  hosts: archive_mirrors
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: unbound }
    - { role: syncarchive, tags: ['nginx'] }
    - { role: zabbix_agent, tags: ["zabbix"] }
    - { role: archive, archive_nginx_only: true, archive_dir: "/srv/archive"}
