---

- name: setup aur-dev.archlinux.org
  hosts: aur-dev.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: mariadb, mariadb_innodb_buffer_pool_size: '64M', mariadb_table_open_cache: '256', mariadb_query_cache_type: '0',
              mariadb_innodb_file_per_table: True }
    - { role: sudo }
    - { role: php-fpm, php_extensions: ['apcu', 'iconv', 'mysqli', 'pdo_mysql'], zend_extensions: ['opcache'] }
    - { role: borg-client, tags: ["borg"] }
    - { role: postfix, postfix_relayhost: "orion.archlinux.org" }
    - { role: fail2ban }
    - { role: aurweb, aurweb_domain: 'aur-dev.archlinux.org', aurweb_version: 'pu' }
