---

- name: setup aur-dev.archlinux.org
  hosts: aur-dev.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: sshd, sshd_enable_includes: true }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: mariadb }
    - { role: sudo }
    - { role: redis }
    - { role: uwsgi }
    - { role: borg_client, tags: ["borg"] }
    - { role: postfix_null }
    - { role: fail2ban }
    - { role: aurweb, aurweb_domain: 'aur-dev.archlinux.org', aurweb_version: 'pu' }
    - { role: prometheus_exporters }
    - { role: promtail }
    - { role: wireguard }
