---

- name: setup aur.archlinux.org
  hosts: aur.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: sshd, sshd_enable_includes: true }
    - { role: root_ssh }
    - { role: prometheus_exporters }
    - { role: promtail }
    - { role: certbot }
    - { role: nginx }
    - { role: mariadb, mariadb_innodb_buffer_pool_size: '1G' }
    - { role: sudo }
    - { role: php_fpm, php_extensions: ['iconv', 'memcached', 'mysqli', 'pdo_mysql'], zend_extensions: ['opcache'] }
    - { role: memcached }
    - { role: uwsgi }
    - { role: borg_client, tags: ["borg"] }
    - { role: postfix_null }
    - { role: fail2ban }
    - { role: aurweb }
    - { role: wireguard }
