---

- name: setup bbs.archlinux.org
  hosts: bbs.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: mariadb, mariadb_innodb_buffer_pool_size: '64M', mariadb_table_open_cache: '256', mariadb_query_cache_type: '0',
              mariadb_innodb_file_per_table: True }
    - { role: sudo }
    - { role: php-fpm, php_extensions: ['apcu', 'iconv', 'intl', 'mysqli'], zend_extensions: ['opcache'], tags: ["php-fpm"] }
    - { role: fluxbb, tags: ["fluxbb"] }
    - { role: borg-client, tags: ["borg"] }
    - { role: postfix, tags: ["postfix"], postfix_relayhost: "orion.archlinux.org" }
