---
- name: disable ABS
  hosts: orion
  remote_user: root
  vars:
    dbscripts_update: no
  roles:
    - { role: dbscripts, repos_domain: "repos.archlinux.org", repos_rsync_domain: "rsync.archlinux.org", svntogit_repos: "/srv/svntogit/repos", postgres_ssl: 'on', tags: ['dbscripts', 'archusers'] }
  tasks:
    - name: disable timer
      service: name=update-abs.timer state=stopped enabled=no

    - name: remove related files
      file: path={{ item }} state=absent
      with_items:
        - /etc/systemd/system/update-abs.timer
        - /etc/systemd/system/update-abs.service
        - /usr/local/bin/update-abs.sh

    - name: reload systemd
      command: systemctl daemon-reload

    - name: remove /srv/abs
      file: path=/srv/abs state=absent
