---

- name: setup gemini.archlinux.org
  hosts: gemini.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg-client, tags: ['borg'] }
    - { role: sudo, tags: ['archusers'] }
    - { role: zabbix-agent }
    - { role: certbot }
    - { role: nginx }
    - { role: sources, sources_domain: "sources.archlinux.org", sources_dir: "/srv/sources" }
    - { role: archive }
    - { role: fail2ban }
