---

- name: setup gemini.archlinux.org
  hosts: gemini.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg-client, tags: ['borg'] }
