---
- name: setup gitlab-runners
  hosts: gitlab_runners
  remote_user: root
  roles:
    - { role: common }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: gitlab-runner }
