---

- name: setup Hetzner storagebox account
  hosts: localhost
  gather_facts: false
  roles:
    - role: hetzner_storagebox
      backup_clients: "{{ groups['borg_clients'] }}"
      backup_dir: backup
      storagebox_id: "{{ hetzner_storagebox_id }}"
      storagebox_hostname: "{{ hetzner_storagebox_username }}.your-storagebox.de"
      storagebox_username: "{{ hetzner_storagebox_username }}"
      storagebox_password: "{{ hetzner_storagebox_password }}"
      tags: ["borg"]
