---

- name: setup luna
  hosts: luna.archlinux.org
  remote_user: root
  tasks:
    - name: open firewall holes for services
      firewalld: service={{item}} permanent=true state=enabled immediate=yes
      with_items:
        - zabbix-agent
        - http
        - https
        - rsyncd
        - smtp
        - git
      when: configure_firewall
      tags:
        - firewall

    - name: open firewall holes for ports
      firewalld: port={{item}} permanent=true state=enabled immediate=yes
      with_items:
        - 6969/tcp
        - 4949/tcp
      when: configure_firewall
      tags:
        - firewall
  roles:
    - nginx
    - spampd
    - { role: mariadb, mariadb_innodb_buffer_pool_size: '64M', mariadb_table_open_cache: '256', mariadb_query_cache_type: '0',
              mariadb_innodb_file_per_table: True }
