- name: setup mail.archlinux.org
  hosts: mail.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg_client, tags: ['borg'] }
    - { role: certbot }
    - { role: nginx }
    - { role: mta_sts }
    - { role: postfix, postfix_server: true, postfix_smtpd_public: true, tags: ['mail'] }
    - { role: dovecot }
    - { role: rspamd, rspamd_dkim_domain: archlinux.org, tags: ["mail"] }
    - { role: unbound, unbound_port: 5353, tags: ["mail"] }
    - { role: postfwd, tags: ['mail'] }
    - { role: archusers }
    - { role: fail2ban }
    - { role: prometheus_exporters }
    - { role: promtail }
    - { role: wireguard }
