---

- name: setup mailman.archlinux.org
  hosts: mailman3.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: sudo }
    - { role: borg-client }
    - { role: postfix, postfix_relayhost: "orion.archlinux.org" }
    - { role: fail2ban }
    - role: postgres
      postgres_max_connections: 100
      postgres_ssl: 'off'
      postgres_shared_buffers: 512MB
      postgres_effective_cache_size: 1GB
    - { role: mailman }
