---

- name: setup matrix
  hosts: matrix.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: unbound }
    - { role: root_ssh }
    - { role: borg-client, tags: ["borg"] }
    - { role: certbot }
    - { role: nginx }
    - role: postgres
      postgres_shared_buffers: 1024MB
      postgres_work_mem: 64MB
      postgres_maintenance_work_mem: 1GB
      postgres_effective_cache_size: 3GB
    - { role: matrix, tags: ['matrix'] }
    - { role: zabbix-agent, tags: ["zabbix"] }
