---
- name: common playbook for mirrors
  hosts: mirrors
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: syncrepo, tags: ['nginx'] }
    - { role: archweb, archweb_site: false, archweb_services: false, archweb_mirrorcheck: true }
    - { role: prometheus_exporters }
    - { role: promtail }
    - { role: fail2ban }
    - { role: wireguard }
