---
- name: common playbook for mirrors
  hosts: mirrors
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: nginx, letsencrypt_validation_dir: "/var/lib/letsencrypt", tags: ["nginx"] }
    - { role: syncrepo, tags: ['syncrepo', 'nginx'] }
    # - { role: zabbix-agent, tags: ["zabbix", "zabbix-agent"] }
