---

- name: setup mirror load balancer (using geoip)
  hosts: mirror.pkgbuild.com
  remote_user: root
  roles:
    - { role: common }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: sudo }
    - { role: zabbix-agent, when: "'unmanaged' not in group_names" }
    - { role: certbot }
    - { role: nginx }
    - { role: mirror_load_balancer }
