---

- name: setup mirror load balancer
  hosts: mirror.pkgbuild.com
  remote_user: root
  roles:
    - { role: common }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: mirror_load_balancer }
