---
- name: common playbook for mirrors
  hosts: mirrors
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: nginx }
    - { role: syncrepo, tags: ['nginx'] }
    - { role: archweb, archweb_site: false, archweb_services: false, archweb_mirrorcheck: true }
    - { role: zabbix-agent, tags: ["zabbix"] }
    - { role: arch32_mirror, tags: ['nginx'] }
