---

- name: setup nymeria
  hosts: nymeria.archlinux.org
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: nginx, tags: ["nginx"] }
    - { role: postgres, postgres_max_connections: 1000, postgres_shared_buffers: 4096MB,
              tags: ['postgres'] }
    - { role: uwsgi, tags: ['uwsgi'] }
    - { role: opendkim, dkim_selector: nymeria, tags: ['mail'] }
    - { role: postfix, postfix_server: false, postfix_smtpd_public: false, tags: ['mail'] }
    - { role: memcached, tags: ['memcached'] }
    - { role: archweb, archweb_repository: "https://github.com/archlinux/archweb.git", archweb_version: "196b1fd8950abe9137e1583f172090b888d487ef", archweb_server_email: 'archweb-dev@archlinux.org', archweb_services: false, archweb_mirrorcheck: true, archweb_mirrorcheck_locations: [5, 6], archweb_domain: 'archweb-dev.archlinux.org', tags: ["archweb"] }
