---

- name: setup openpgpkey server
  hosts: openpgpkey.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: certbot }
    - { role: nginx }
    - { role: wkd }
    - { role: prometheus_exporters }
