---

- name: setup orion
  hosts: orion
  remote_user: root
  vars:
    archweb_db_host: 'apollo.archlinux.org'
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: borg-client, backup_host: "borg@vostok.archlinux.org", backup_dir: "/backup/orion", postgres_backup_dir: None, tags: ['borg'] }
    - { role: opendkim, dkim_selector: orion, tags: ['mail'] }
    - { role: postfix, postfix_server: false, tags: ['mail'] }
    - { role: archusers, tags: ['archusers'] }
    - { role: nginx, letsencrypt_validation_dir: "/var/lib/letsencrypt", tags: ["nginx"] }
    - { role: dbscripts, repos_domain: "repos.archlinux.org", svntogit_repos: "/srv/svntogit/repos", tags: ['dbscripts', 'archusers'] }
    - { role: sudo, tags: ['sudo', 'archusers'] }
    - { role: archweb, archweb_site: false, archweb_services: true, archweb_mirrorcheck_locations: [5, 6], tags: ['archweb'] }
    - { role: sources, sources_domain: "sources.archlinux.org", sources_dir: "/srv/sources", tags: ['sources'] }
