---

- name: setup orion
  hosts: orion
  remote_user: root
  roles:
    - common
    - tools
    - sshd
    - ssh_keys
    - { role: borg-client, backup_host: "root@vostok.archlinux.org", backup_dir: "/backup/orion" }
