---

- name: setup orion
  hosts: orion
  remote_user: root
  roles:
    - common
    - tools
    - sshd
    - ssh_keys
    - { role: borg-client, backup_host: "borg@vostok.archlinux.org", backup_dir: "/backup/orion", postgres_backup_dir: None }
    - { role: opendkim, dkim_selector: orion }
    - { role: postfix}
    - archusers
    - dbscripts
    - sudo
    - nginx
