---

- name: setup orion
  hosts: orion
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: borg-client, backup_host: "borg@vostok.archlinux.org", backup_dir: "/backup/orion", postgres_backup_dir: None, tags: ['borg'] }
    - { role: opendkim, dkim_selector: orion, tags: ['mail'] }
    - { role: postfix, tags: ['mail'] }
    - { role: archusers, tags: ['archusers'] }
    - { role: nginx, tags: ["nginx"] }
    - { role: dbscripts, repos_domain: "repos.archlinux.org", tags: ['dbscripts', 'archusers'] }
    - { role: sudo, tags: ['sudo', 'archusers'] }
    - { role: archweb, archweb_home: "/srv/http/archweb", tags: ['archweb'] }
