---

- name: setup orion
  hosts: orion.archlinux.org
  remote_user: root
  vars:
    archweb_db_host: 'apollo.archlinux.org'
    dbscripts_commit: '20191022'
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg-client, tags: ['borg'] }
    - { role: opendkim, dkim_selector: orion, tags: ['mail'] }
    - { role: dovecot }
    - { role: spampd, tags: ["mail"] }
    - { role: postgrey, tags: ["mail"] }
    - { role: unbound, tags: ["mail"] }
    - { role: postfwd, tags: ['mail'] }
    - { role: postfix, postfix_server: true, postfix_smtpd_public: true, tags: ['mail'] }
    - { role: archusers }
    - { role: certbot }
    - { role: nginx }
    - { role: dbscripts, repos_domain: "repos.archlinux.org", repos_rsync_domain: "rsync.archlinux.org", svntogit_repos: "/srv/svntogit/repos", postgres_ssl: 'on', tags: ['archusers'] }
    - sogrep
    - { role: sudo, tags: ['archusers'] }
    - { role: archweb, archweb_site: false, archweb_services: true, archweb_donor_import: true, archweb_mirrorcheck_locations: [5, 6] }
    - { role: sources, sources_domain: "sources.archlinux.org", sources_dir: "/srv/sources" }
    - { role: hefur, ftp_iso_dir: '/srv/ftp/iso', tags: ['torrenttracker']}
    - wkd
    - { role: fail2ban }
