---

- name: setup phrik bot server
  hosts: phrik.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: archusers }
    - { role: bugbot }
    - { role: phrik }
    - { role: sshd }
    - { role: unbound }
    - { role: root_ssh }
    - { role: prometheus_exporters }
