---

- name: setup rsync.net account
  hosts: localhost
  gather_facts: false
  roles:
    - role: rsync_net
      backup_clients: "{{ groups['borg_clients'] }}"
      backup_dir: backup
      tags: ["borg"]
