---

- name: setup rsync.net account
  hosts: zh1905.rsync.net
  gather_facts: false
  roles:
    - { role: rsync_net, backup_dir: "backup", backup_clients: "{{ groups['borg_clients'] }}", tags: ["borg"] }
