---

- name: setup soyuz
  hosts: soyuz.archlinux.org
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: unbound }
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: borg-client, tags: ['borg'] }
    - { role: opendkim, dkim_selector: soyuz, tags: ['mail'] }
    - { role: postfix, postfix_server: false, tags: ["mail", "postfix"] }
    - { role: archusers, tags: ['archusers'] }
    - { role: certbot }
    - { role: nginx, tags: ["nginx"] }
    - { role: sudo, tags: ['sudo', 'archusers'] }
    - { role: sogrep, tags: ['sogrep'] }
    - { role: archbuild, tags: ['archbuild'] }
    - { role: public_html, public_domain: "pkgbuild.com", tags: ['public_html', 'nginx'] }
    - { role: crond, tags: ['crond'] }
    - { role: arch-boxes, tags: ['arch-boxes'] }
    - { role: docker-image }
