---

- name: setup soyuz
  hosts: soyuz
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: borg-client, backup_host: "borg@vostok.archlinux.org", backup_dir: "/backup/soyuz", postgres_backup_dir: None, tags: ['borg'] }
    - { role: archusers, tags: ['archusers'] }
    - { role: nginx, letsencrypt_validation_dir: "/var/lib/letsencrypt", tags: ["nginx"] }
    - { role: sudo, tags: ['sudo', 'archusers'] }
    - { role: postgres, tags: ['postgres'] }
    - { role: quassel, quassel_domain: "quassel.archlinux.org", tags: ['quassel'] }
    - { role: syncrepo, tags: ['syncrepo'] }
    - { role: sogrep, tags: ['sogrep'] }
