---

- name: setup state.archlinux.org (terraform state store)
  hosts: state.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: unbound }
    - { role: certbot }
    - { role: borg-client, tags: ["borg"] }
    - { role: zabbix-agent, tags: ["zabbix"] }
    - { role: root_ssh }
    - role: postgres
      postgres_listen_addresses: "*"
      postgres_max_connections: 100
      postgres_ssl: 'on'
      postgres_shared_buffers: 512MB
      postgres_ssl_hosts4: ['0.0.0.0/0']
      postgres_ssl_hosts6: ['::/0']
    - { role: terraform_state }
