---

- name: setup terraform-state
  hosts: service-terraform-state
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: firewalld, tags: ['firewall'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: unbound }
    - { role: certbot }
    - { role: root_ssh, tags: ['root_ssh'] }
    - role: postgres
      postgres_listen_addresses: "*"
      postgres_max_connections: 100
      postgres_ssl: 'on'
      postgres_shared_buffers: 512MB
      postgres_ssl_hosts4: ['0.0.0.0/0']
      postgres_ssl_hosts6: ['::/0']
      tags: ['postgres']
