---

- name: "prepare postgres ssl hosts list"
  hosts: apollo.archlinux.org
  tasks:
      - set_fact: postgres_ssl_hosts4="0.0.0.0/0"
      - set_fact: postgres_ssl_hosts6="::/0"

- name: setup terraform-state
  hosts: service-terraform-state
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: firewalld, tags: ['firewall'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: unbound }
    - { role: certbot }
    - { role: root_ssh, tags: ['root_ssh'] }
    - role: postgres
      postgres_listen_addresses: "*"
      postgres_max_connections: 100
      postgres_ssl: 'on'
      postgres_shared_buffers: 512MB
      tags: ['postgres']
