---

- name: setup vostok
  hosts: vostok
  remote_user: root
  roles:
    - common
    - tools
    - sshd
    - root_ssh
    - { role: borg-server, backup_dir: "/backup", backup_clients: ["orion", "apollo"] }
