---

- name: setup vostok
  hosts: vostok.archlinux.org
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - tools
    - sshd
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: borg-server, backup_dir: "/backup", backup_clients: ["orion", "apollo", "soyuz"] }
