---

aurweb_domain: 'aur.archlinux.org'
aurweb_repository: 'https://git.archlinux.org/aurweb.git'
tubylaws_repository: 'https://git.archlinux.org/tu-bylaws.git'
aurweb_dir: '/srv/http/aurweb'
aurweb_conf_dir: '/etc/aurweb'
aurweb_git_dir: "{{ aurweb_dir }}/aur.git"
aurweb_git_hook: '/usr/local/bin/aurweb-git-update'
aurweb_nginx_conf: '/etc/nginx/nginx.d/aurweb.conf'
aurweb_version: 'live'
tubylaws_version: 'proposal-117'

aurweb_db: 'aur'
aurweb_db_host: 'localhost'
aurweb_db_user: 'aur'

aurweb_user: 'aur'
aurweb_socket: '/run/php-fpm/{{aurweb_user}}.socket'
cgit_socket: '/run/uwsgi/cgit.sock'

aurweb_cache: 'apc'
aurweb_cache_pkginfo_ttl: '86400'
aurweb_request_limt: '4000'
aurweb_window_length: '86400'
aurweb_apc_shm_size: '1024M'
aurweb_apc_ttl: '1800'
aurweb_apc_entries_hint: '0'
