---

- name: install binutils
  pacman: name=binutils state=present

- name: install sogrep scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - createlinks
    - sogrep

- name: install sogrep units
  copy: src={{ item }} dest=/etc/systemd/system/{{ item }} owner=root group=root mode=0644
  with_items:
    - createlinks.timer
    - createlinks.service
  notify:
    - daemon reload

- name: start and enable sogrep units
  service: name=createlinks.timer enabled=yes state=started
