---

- name: install phrik utilities
  pacman: name=git,pkgfile state=present

- name: add phrik group
  group: name=phrik gid=1100 state=present

- name: add phrik user
  user: name=phrik group=phrik uid=1100 comment="phrik IRC bot" createhome=yes

- name: adding users to phrik group
  user: groups=phrik name="{{ item }}" append=yes
  with_items:
    - demize
  tags: ['archusers']

- name: adding users to systemd-journal group for monitoring
  user: groups=systemd-journal name="{{ item }}" append=yes
  with_items:
    - demize
  tags: ['archusers']

- name: install phrik sudoers config
  copy: src=sudoers dest=/etc/sudoers.d/phrik

- name: install polkit rule for restarting phrik
  copy: src=20-manage-phrik.rules dest=/etc/polkit-1/rules.d/20-manage-phrik.rules

- name: install phrik systemd service
  copy: src=phrik.service dest=/etc/systemd/system/phrik.service
  notify:
    - daemon reload

- name: start and enable pkgfile service
  service: name="pkgfile-update.service" enabled=yes state=started

- name: start and enable phrik service
  service: name="phrik.service" enabled=yes state=started
