---

- name: install phrik utilities
  pacman: name=git state=present

- name: add phrik group
  group: name=phrik gid=1100 state=present

- name: add phrik user
  user: name=phrik group=phrik uid=1100 comment="phrik IRC bot" createhome=yes

- name: ading users to phrik group
  user: groups=phrik name="{{ item }}" append=yes
  with_items:
    - demize
  tags: ['archusers']

- name: install phrik sudoers config
  copy: src=sudoers dest=/etc/sudoers.d/phrik
